export const dynamic = "force-dynamic";

import { WorkOrderStatus } from "@prisma/client";
import { fail, ok } from "@/lib/http";
import { prisma } from "@/lib/prisma";

export async function GET(request: Request) {
  const url = new URL(request.url);
  const truckId = url.searchParams.get("truckId") ?? undefined;
  const status = (url.searchParams.get("status") as WorkOrderStatus | null) ?? undefined;

  const workOrders = await prisma.workOrder.findMany({
    where: {
      ...(truckId ? { truckId } : {}),
      ...(status ? { status } : {})
    },
    include: {
      truck: {
        select: {
          id: true,
          truckNumber: true,
          currentOdometer: true
        }
      },
      maintenanceType: true,
      assignedTo: {
        select: {
          id: true,
          name: true
        }
      },
      serviceHistory: true
    },
    orderBy: [{ status: "asc" }, { createdAt: "desc" }],
    take: 300
  });

  const enriched = workOrders.map((wo) => {
    const overdueMiles = Math.max(0, wo.truck.currentOdometer - wo.dueAtOdometer);

    return {
      ...wo,
      overdueMiles,
      visualState:
        wo.status === WorkOrderStatus.COMPLETED || wo.status === WorkOrderStatus.CANCELLED
          ? wo.status
          : overdueMiles > 0
            ? "OVERDUE"
            : "DUE"
    };
  });

  return ok(enriched);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const truckId = body.truckId as string | undefined;
    const maintenanceTypeId = body.maintenanceTypeId as string | undefined;

    if (!truckId || !maintenanceTypeId) {
      return fail("truckId y maintenanceTypeId son obligatorios", 400);
    }

    const duplicateOpen = await prisma.workOrder.findFirst({
      where: {
        truckId,
        maintenanceTypeId,
        status: {
          in: [WorkOrderStatus.PENDING, WorkOrderStatus.IN_PROGRESS]
        }
      }
    });

    if (duplicateOpen) {
      return fail("Ya existe una orden abierta para ese camión y mantenimiento", 409);
    }

    const truck = await prisma.truck.findUnique({ where: { id: truckId } });
    if (!truck) return fail("Camión no encontrado", 404);

    const created = await prisma.workOrder.create({
      data: {
        workorderNumber: `MANUAL-${Date.now()}`,
        truckId,
        maintenanceTypeId,
        dueAtOdometer: truck.currentOdometer,
        autoGenerated: false
      }
    });

    return ok(created, { status: 201 });
  } catch (error) {
    return fail("No se pudo crear la orden", 400, String(error));
  }
}
