export type UserRole = "ADMIN" | "OPERATOR" | "MECHANIC";
export type TruckStatus = "ACTIVE" | "INACTIVE" | "OUT_OF_SERVICE";
export type WorkOrderStatus = "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";

export type User = {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  createdAt: string;
};

export type Truck = {
  id: string;
  truckNumber: string;
  brand: string;
  model: string;
  year: number;
  currentOdometer: number;
  status: TruckStatus;
  createdAt: string;
  updatedAt: string;
};

export type YardEntry = {
  id: string;
  truckId: string;
  datetime: string;
  odometer: number;
  computedDelta: number;
  recordedById: string;
  notes?: string;
  photoUrl?: string;
  createdAt: string;
  updatedAt: string;
};

export type MaintenanceType = {
  id: string;
  name: string;
  intervalMiles: number;
  warningBeforeMiles: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type TruckMaintenanceState = {
  id: string;
  truckId: string;
  maintenanceTypeId: string;
  lastServiceOdometer: number;
  lastServiceAt?: string;
  createdAt: string;
  updatedAt: string;
};

export type WorkOrder = {
  id: string;
  serialNumber: number;
  workorderNumber: string;
  truckId: string;
  maintenanceTypeId: string;
  status: WorkOrderStatus;
  createdAt: string;
  dueAtOdometer: number;
  completedAt?: string;
  assignedToId?: string;
  createdFromEntryId?: string;
  autoGenerated: boolean;
};

export type ServiceHistory = {
  id: string;
  truckId: string;
  maintenanceTypeId: string;
  workorderId: string;
  performedAt: string;
  odometerAtService: number;
  performedById: string;
  notes?: string;
  attachmentUrl?: string;
};

export type AuditLog = {
  id: string;
  entityType: string;
  entityId: string;
  oldValue: Record<string, unknown>;
  newValue: Record<string, unknown>;
  changedById: string;
  reason: string;
  timestamp: string;
};

export type LocalDbState = {
  meta: {
    workOrderSerial: number;
  };
  users: User[];
  trucks: Truck[];
  yardEntries: YardEntry[];
  maintenanceTypes: MaintenanceType[];
  truckMaintenanceStates: TruckMaintenanceState[];
  workOrders: WorkOrder[];
  serviceHistory: ServiceHistory[];
  auditLogs: AuditLog[];
  currentActorId: string;
};

export type HealthState = "OK" | "DUE_SOON" | "DUE" | "OVERDUE";
